ess-dmsc/file-writer-control

file_writer_control/JobStatus.py, tests/test_job_status.py
First PR. Adds two classes for keeping track of (write) jobs.
=> Add JobStatus

file_writer_control/CommandStatus.py, tests/test_command_status.py
As the title says: two classes for keeping track of (write) jobs.
=> Added command status.

file_writer_control/WorkerStatus.py, tests/test_worker_status.py
=> Added worker status

file_writer_control/KafkaTopicUrl.py, tests/test_kafka_topic_url.py
=> Added Kafka topic URL parser

file_writer_control/StateExtractor.py, tests/test_state_extractor.py
* As the title says. For extracting worker/job/command states from file-writer updates.
=> Added state extractor code.

file_writer_control/WriteJob.py, requirements.txt, tests/test_write_job.py
As the title says. Nothing weird here.
=> Add write job representation

file_writer_control/InThreadStatusTracker.py, tests/test_in_thread_status_tracker.py
=> Threaded file-writer status tracker.

file_writer_control/CommandChannel.py, tests/test_command_channel.py, tests/test_in_thread_status_tracker.py
Also: removed unit test that should have been removed in the previous PR.
=> Added command channel

file_writer_control/CommandHandler.py, tests/test_command_handler.py
=> Added command handler

file_writer_control/CommandId.py, tests/test_command_id.py
A simple function for generating a command id and a unit test of this function.
=> Command id generator

file_writer_control/WorkerFinder.py, tests/test_worker_finder.py
=> Add worker finder base class

file_writer_control/JobHandler.py, tests/test_job_handler.py
=> Add job handler

file_writer_control/WorkerCommandChannel.py, file_writer_control/utilities/context_managers.py, tests/test_worker_command_channel.py
This implements a context manager to handle sleep times for control flow.
=> Implement context manager

file_writer_control/WorkerCommandChannel.py, file_writer_control/utilities/context_managers.py, tests/test_worker_command_channel.py
A bit of contortion was required for making unit testing possible.
=> Added worker command channel

file_writer_control/CommandStatus.py, file_writer_control/InThreadStatusTracker.py, file_writer_control/JobStatus.py, file_writer_control/WorkerStatus.py, tests/test_command_channel.py
Some commands were sometimes not properly "timed out". This change should make sure that timeouts are pushed through.
=> Fix of timeout issue.

CHANGES.md, file_writer_control/WorkerFinder.py, file_writer_control/WorkerJobPool.py, setup.py
=> Better exceptions.

CHANGES.md, README.md, examples/list_status.py, examples/write_job_1.py, examples/write_job_2.py, examples/write_job_w_error_checking.py, file_writer_control/InThreadStatusTracker.py, file_writer_control/JobStatus.py, file_writer_control/WorkerCommandChannel.py, file_writer_control/__init__.py, file_writer_control/_version.py, requirements.txt, setup.py, tests/test_worker_command_channel.py
Various minor changes. See the "CHANGES.md" file. Should probably have been two PRs but I forgot about one of them so I decided to merge the two.
=> Resolving com issues

CHANGES.md, README.md, file_writer_control/JobStatus.py, file_writer_control/WorkerFinder.py, file_writer_control/WorkerJobPool.py, file_writer_control/__init__.py, file_writer_control/_version.py, setup.py
* Added the version to the installed package.
* Minor exception message improvements.
* Minor documentation updates.
=> Various minor fixes.

README.md, examples/job_pool.py, file_writer_control/WriteJob.py, requirements-dev.txt
The change is simple, but I also tidied up the docs and the requirements so there is a few more changes.
=> Specify the control topic when starting a new job.

CHANGES.md, file_writer_control/WorkerJobPool.py, file_writer_control/_version.py
=> Configurable message size.
